apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-image-app
  namespace: server2  
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: chat-image
  template:
    metadata:
      labels:
        app: chat-image
    spec:
      containers:
        - name: chat-image-container
          image: moath32/image:1.0
          ports:
            - containerPort: 8000
              name: image-port
          resources:
            limits:
              memory: "100Mi"
              cpu: "80m"
            requests:
              memory: "64Mi"
              cpu: "50m"