apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-tls
  namespace: argocd
spec:
  secretName: argo-cd-tls
  issuerRef:
    name: letsencrypt-innocode
    kind: ClusterIssuer
  dnsNames:
    - argocd.genio.ae
